name: Mi Primer Workflow

on:
    push:
        branches:
            - master
    workflow_dispatch:


jobs:
    saludar:
        runs-on: ubuntu-latest
        steps:
            - name: Saludar
              run: echo "Hola Mundo"
            - name: Check files
              uses: ls
            - name: Check out the repository
              uses: actions/checkout@v4
            - name: Check files
              uses: ls